services:
  # 1. The Spring Boot Monolith Application Web Service
  - type: web
    name: entos-cafe-api-dev
    env: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    plan: free
    region: singapore
    healthCheckPath: /api/actuator/health
    envVars:
      - key: PORT
        value: 10000

      # This bypasses the embedded user/password string completely!
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: entos-postgres-db-dev
          property: connectionString

      - key: DB_INTERNAL_HOST
        fromDatabase:
          name: entos-postgres-db-dev
          property: host

      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: entos-postgres-db-dev
          property: user

      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: entos-postgres-db-dev
          property: password

      - key: JWT_SECRET
        sync: false
      - key: OAUTH2_GOOGLE_CLIENT_ID
        sync: false
      - key: OAUTH2_GOOGLE_CLIENT_SECRET
        sync: false

databases:
  # 2. The Private Managed PostgreSQL Instance
  - name: entos-postgres-db-dev
    databaseName: entos_db_dev
    user: entos_admin
    plan: free
    region: singapore