services:
  # 1. The Spring Boot Monolith Application Web Service (DEV Environment)
  - type: web
    name: entos-cafe-api-dev
    env: docker
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    plan: free
    region: singapore
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: dev                        # ⚡ Kept as dev for your DEV server!
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: entos-postgres-db-dev
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: OAUTH2_GOOGLE_CLIENT_ID
        sync: false
      - key: OAUTH2_GOOGLE_CLIENT_SECRET
        sync: false
      - key: PORT
        value: 8083

databases:
  # 2. The Private Managed PostgreSQL Instance (DEV Environment)
  - name: entos-postgres-db-dev
    databaseName: entos_db_dev
    user: entos_admin
    plan: free
    region: singapore
