spring:
  application:
    name: entos-cafe-platform

  # This is the modern way to activate multiple module files
  config:
    import:
      - "optional:classpath:application-identity.yml"
      - "optional:classpath:application-api.yml"
      - "optional:classpath:application-shared.yml"
      - "optional:classpath:application-infra.yml"
      - "optional:classpath:application-platform.yml"
      - "optional:classpath:application-cafe.yml"

  # Default profile when no profile is explicitly set
  profiles:
    active: dev

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

---
# --- Development Specific Overrides ---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: ${PORT:8081}